Diego
Sebazt/pets-care-frontend pull request #6
Opened 2022-11-11 22:16 UTC by Choklitos21

AboutServices creado, mostrando texto quemado sobre los 3 servicios que prestamos. 
En el side bar coloque don iconos para ir a home y a AbourServices, agregue dos valores al sidebar para que el texto no hiciera brincar el sidebar

2022-11-11 22:43 UTC, Thelimon requested changes

2022-11-11 22:43 UTC, Thelimon commented on src/app/common-components/sidenav/sidenav.component.scss
>      .sidenav-nav-link:hover {
Esto lo puede mejorar al estar usando Scss, en el bloque de código de ` .side-nav-link` puede usar esto.

.side-nav-link{
   &:hover{
        ... estilos que creó.
    }
}

2022-11-11 22:43 UTC, Thelimon commented on src/app/common-components/sidenav/sidenav.component.scss
>          color: #fff;
No usemos colores quemados, cree una variable `$white: #fff` y la cambia acá.

2022-11-11 22:43 UTC, Thelimon commented on src/app/common-components/sidenav/sidenav.component.scss
>        color: #fff;
No usemos colores quemados, cree una variable $white: #fff y la cambia acá.

2022-11-11 22:43 UTC, Thelimon commented on src/app/common-components/sidenav/sidenav.component.scss
>        color: #000;
No colores quemados.

2022-11-11 22:43 UTC, Thelimon commented on src/app/common-components/sidenav/sidenav.component.scss
>        background-color: #fff;
No colores quemados.

2022-11-11 22:43 UTC, Thelimon commented on src/app/home/about-services/about-services.component.ts
> +  constructor() { }
Si no hay inyecciones de dependencias, eliminar el constructor vacío.

2022-11-11 22:43 UTC, Thelimon commented on src/app/home/about-services/about-services.component.ts
> +  ngOnInit(): void {
Si no hay nada en el ngOnInit, eliminarlo.

2022-11-11 22:43 UTC, Thelimon commented on src/app/home/about-services/about-services.component.scss
> +  color: white;
No colores quemados

2022-11-11 22:43 UTC, Thelimon commented on src/app/home/about-services/about-services.component.html
> +  <div *ngFor="let card of cards" class="card mb-5 shadow p-3 mb-5 bg-body rounded" style="max-width: 100%">
Esto se puede mejorar, si la card va a ser un elemento reutilizable es mejor crear un componente común y aplicar un ngFor sobre el selector de ese componente, pasando como input el iterador de esa iteración.

![imagen](https://user-images.githubusercontent.com/56146135/201440171-ec2429ed-03b9-4ed3-bf74-1a6349388a7b.png)

Ignorar los errores, solo es un ejemplo, ajustar al escenario actual.

2022-11-11 22:43 UTC, Thelimon commented on src/app/home/home.component.ts
Cuidado con los espacios en blanco

2022-11-12 13:21 UTC, Choklitos21 commented on src/app/common-components/sidenav/sidenav.component.scss
>      .sidenav-nav-link:hover {
Fixed

2022-11-12 13:23 UTC, Choklitos21 commented on src/app/common-components/sidenav/sidenav.component.scss
>          color: #fff;
fixed $color-white added

2022-11-12 13:23 UTC, Choklitos21 commented on src/app/common-components/sidenav/sidenav.component.scss
>        color: #fff;
fixed

2022-11-12 13:24 UTC, Choklitos21 commented on src/app/common-components/sidenav/sidenav.component.scss
>        color: #000;
fixed :)

2022-11-12 13:24 UTC, Choklitos21 commented on src/app/common-components/sidenav/sidenav.component.scss
>        background-color: #fff;
fixed :)

2022-11-12 13:25 UTC, Choklitos21 commented on src/app/home/about-services/about-services.component.ts
> +  constructor() { }
fixed

2022-11-12 13:25 UTC, Choklitos21 commented on src/app/home/about-services/about-services.component.ts
> +  ngOnInit(): void {
fixed

2022-11-12 13:26 UTC, Choklitos21 commented on src/app/home/about-services/about-services.component.scss
> +  color: white;
fixed

2022-11-12 13:26 UTC, Choklitos21 commented on src/app/home/about-services/about-services.component.html
> +  <div *ngFor="let card of cards" class="card mb-5 shadow p-3 mb-5 bg-body rounded" style="max-width: 100%">
Thanks

2022-11-12 13:28 UTC, Choklitos21 commented on src/app/home/home.component.ts
Ty

2022-11-12 15:14 UTC, merged